# Generated by Django 3.2.3 on 2021-06-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20210627_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='running_balance',
            field=models.BigIntegerField(default=0, verbose_name='Текущий баланс'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='current_balance',
            field=models.BigIntegerField(default=0, verbose_name='Баланс счета'),
        ),
    ]
