# Generated by Django 3.2.3 on 2021-07-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
