# Generated by Django 3.2.3 on 2021-07-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_transaction_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purpose',
            options={'verbose_name': 'Назначение', 'verbose_name_plural': 'Назначение'},
        ),
    ]
