# Generated by Django 3.2.3 on 2021-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20210706_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='kgcoin_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Количество монеты'),
        ),
    ]
