# Generated by Django 3.2.3 on 2021-07-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_auto_20210707_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество монеты'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='current_balance',
            field=models.FloatField(default=0, verbose_name='Баланс счета'),
        ),
    ]
