# Generated by Django 3.2.3 on 2021-07-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0015_wallet_kgcoin_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kgcoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Количество монеты')),
                ('cost', models.DecimalField(decimal_places=2, default=100, max_digits=12, verbose_name='Стоимость монеты')),
            ],
            options={
                'verbose_name': 'KGcoin',
                'verbose_name_plural': 'KGcoins',
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Покупка монеты')),
                ('sell_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Продажа монеты')),
                ('kgcoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kgcoin', to='kgcoin.kgcoin')),
                ('user_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_wallet', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Coin транзакция',
                'verbose_name_plural': 'Coin транзакции',
            },
        ),
    ]
