# Generated by Django 3.2.3 on 2021-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgcoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kgcoin',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название монеты'),
        ),
    ]
