# Generated by Django 3.2.3 on 2021-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgcoin', '0002_kgcoin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kgcoin',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название монеты'),
        ),
    ]
