# Generated by Django 3.2.3 on 2021-07-07 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kgcoin', '0003_alter_kgcoin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания транзакции'),
            preserve_default=False,
        ),
    ]
