# Generated by Django 3.2.3 on 2021-07-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kgcoin', '0004_cointransaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kgcoin',
            name='name',
        ),
    ]
