# Generated by Django 3.2.3 on 2021-07-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgcoin', '0006_alter_cointransaction_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='buy_amount',
            field=models.FloatField(default=0, verbose_name='Покупка монеты'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='sell_amount',
            field=models.FloatField(default=0, verbose_name='Продажа монеты'),
        ),
        migrations.AlterField(
            model_name='kgcoin',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Количество монеты'),
        ),
        migrations.AlterField(
            model_name='kgcoin',
            name='cost',
            field=models.FloatField(default=100, verbose_name='Стоимость монеты'),
        ),
    ]
