# Generated by Django 3.2.3 on 2021-07-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_auto_20210707_2243'),
        ('kgcoin', '0007_auto_20210707_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='user_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_owner', to='wallet.wallet'),
        ),
    ]
