# Generated by Django 3.2.3 on 2021-07-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплата клиента'),
        ),
    ]
