# Generated by Django 3.2.3 on 2021-07-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20210705_2113'),
        ('user', '0004_company_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
